"""Test tools for generating and consuming leanSpec consensus test vectors."""

from collections.abc import Callable

from consensus_testing import forks
from consensus_testing.genesis import (
    build_anchor,
    build_genesis_state,
    build_genesis_store,
)
from consensus_testing.mocks import (
    MockEventSource,
    MockForkchoiceStore,
    MockNetworkRequester,
    RecordedCall,
    RecordingSyncDatabase,
    create_mock_sync_service,
)
from consensus_testing.test_fixtures import (
    FIXTURE_FORMATS,
    ApiEndpointFixture,
    ApiEndpointTest,
    AppendPhantomAttestation,
    BaseConsensusFixture,
    BaseTestSpec,
    ClearFirstAttestationBits,
    CorruptProof,
    DropMessageBinding,
    ExpectedRejection,
    FixtureInfo,
    ForkChoiceFixture,
    ForkChoiceTest,
    GossipsubHandlerFixture,
    GossipsubHandlerTest,
    IncrementEmittedSlot,
    JustifiabilityFixture,
    JustifiabilityTest,
    MutateStateRoot,
    NetworkingCodecFixture,
    NetworkingCodecTest,
    PoseidonPermutationFixture,
    PoseidonPermutationTest,
    ReaggregationFixture,
    ReaggregationTest,
    RebindToAlternateHeadRoot,
    SetProposerIndex,
    SlotClockFixture,
    SlotClockTest,
    SSZFixture,
    SSZTest,
    StateTransitionFixture,
    StateTransitionTest,
    SwapFirstTwoAttestations,
    SwapMessageBindings,
    SwapParticipantPublicKey,
    SyncFixture,
    SyncTest,
    VerifyMultiMessageProofsFixture,
    VerifyMultiMessageProofsTest,
    VerifySignaturesFixture,
    VerifySignaturesTest,
    VerifySingleMessageProofsFixture,
    VerifySingleMessageProofsTest,
)
from consensus_testing.test_fixtures.gossipsub_handler import (
    CachedMessage,
    GossipsubEvent,
    GossipsubInitialState,
    GossipsubMeshParameters,
    IncomingGraft,
    IncomingIDontWant,
    IncomingIHave,
    IncomingIWant,
    IncomingPrune,
    IncomingPublish,
    PeerConfiguration,
)
from consensus_testing.test_fixtures.networking_codec import (
    DecodeFailure,
    EnrRoundtrip,
    GossipMessageIdentifier,
    GossipsubRpcRoundtrip,
    GossipTopicRoundtrip,
    PeerIdentifierDerivation,
    ReqRespRequestRoundtrip,
    ReqRespResponseRoundtrip,
    ReqRespResponseStream,
    ResponseChunkSpec,
    RpcControlSpec,
    RpcGraftSpec,
    RpcIDontWantSpec,
    RpcIHaveSpec,
    RpcIWantSpec,
    RpcMessageSpec,
    RpcPruneSpec,
    RpcSubscriptionSpec,
    SnappyBlockRoundtrip,
    SnappyFrameRoundtrip,
    VarintRoundtrip,
)
from consensus_testing.test_fixtures.slot_clock import (
    CurrentInterval,
    CurrentSlot,
    FromSlot,
    FromUnixTime,
    TotalIntervals,
)
from consensus_testing.test_fixtures.sync import VerifyCheckpoint
from consensus_testing.test_types import (
    AggregatedAttestationCheck,
    AggregatedAttestationSpec,
    AttestationCheck,
    AttestationStep,
    BaseForkChoiceStep,
    BlockSpec,
    BlockStep,
    ForkChoiceStep,
    GossipAggregatedAttestationStep,
    GossipAttestationSpec,
    StateExpectation,
    StoreChecks,
    StoreSnapshot,
    TickStep,
)
from consensus_testing.values import (
    TEST_VALIDATOR_INDEX,
    make_signed_attestation,
    make_signed_block,
    make_test_block,
    make_test_status,
    signed_block_with_empty_proof,
    store_backed_signed_block_getter,
)

StateTransitionTestFiller = Callable[..., StateTransitionFixture]
ForkChoiceTestFiller = Callable[..., ForkChoiceFixture]
VerifySingleMessageProofsTestFiller = Callable[..., VerifySingleMessageProofsFixture]
VerifyMultiMessageProofsTestFiller = Callable[..., VerifyMultiMessageProofsFixture]
VerifySignaturesTestFiller = Callable[..., VerifySignaturesFixture]
SSZTestFiller = Callable[..., SSZFixture]
NetworkingCodecTestFiller = Callable[..., NetworkingCodecFixture]
GossipsubHandlerTestFiller = Callable[..., GossipsubHandlerFixture]
ApiEndpointTestFiller = Callable[..., ApiEndpointFixture]
SlotClockTestFiller = Callable[..., SlotClockFixture]
JustifiabilityTestFiller = Callable[..., JustifiabilityFixture]
PoseidonPermutationTestFiller = Callable[..., PoseidonPermutationFixture]
SyncTestFiller = Callable[..., SyncFixture]
ReaggregationTestFiller = Callable[..., ReaggregationFixture]

__all__ = [
    "CachedMessage",
    "GossipsubEvent",
    "GossipsubInitialState",
    "GossipsubMeshParameters",
    "IncomingGraft",
    "IncomingIDontWant",
    "IncomingIHave",
    "IncomingIWant",
    "IncomingPrune",
    "IncomingPublish",
    "PeerConfiguration",
    "DecodeFailure",
    "EnrRoundtrip",
    "GossipMessageIdentifier",
    "GossipsubRpcRoundtrip",
    "GossipTopicRoundtrip",
    "PeerIdentifierDerivation",
    "ReqRespRequestRoundtrip",
    "ReqRespResponseRoundtrip",
    "ReqRespResponseStream",
    "ResponseChunkSpec",
    "RpcControlSpec",
    "RpcGraftSpec",
    "RpcIDontWantSpec",
    "RpcIHaveSpec",
    "RpcIWantSpec",
    "RpcMessageSpec",
    "RpcPruneSpec",
    "RpcSubscriptionSpec",
    "SnappyBlockRoundtrip",
    "SnappyFrameRoundtrip",
    "VarintRoundtrip",
    "CurrentInterval",
    "CurrentSlot",
    "FromSlot",
    "FromUnixTime",
    "TotalIntervals",
    "ReaggregationFixture",
    "ReaggregationTest",
    "VerifyCheckpoint",
    # Public API
    "AggregatedAttestationSpec",
    "GossipAttestationSpec",
    "BlockSpec",
    "forks",
    "build_anchor",
    "build_genesis_state",
    # Unit-test builders and value constructors
    "build_genesis_store",
    "create_mock_sync_service",
    "TEST_VALIDATOR_INDEX",
    "make_signed_attestation",
    "make_signed_block",
    "make_test_block",
    "make_test_status",
    "signed_block_with_empty_proof",
    "store_backed_signed_block_getter",
    # Unit-test fakes
    "MockEventSource",
    "MockForkchoiceStore",
    "MockNetworkRequester",
    "RecordedCall",
    "RecordingSyncDatabase",
    # Base types
    "FIXTURE_FORMATS",
    "BaseConsensusFixture",
    "BaseTestSpec",
    "ExpectedRejection",
    "FixtureInfo",
    # Spec and fixture classes
    "StateTransitionFixture",
    "StateTransitionTest",
    "ForkChoiceFixture",
    "ForkChoiceTest",
    "VerifySingleMessageProofsFixture",
    "VerifySingleMessageProofsTest",
    "VerifyMultiMessageProofsFixture",
    "VerifyMultiMessageProofsTest",
    "RebindToAlternateHeadRoot",
    "IncrementEmittedSlot",
    "SwapParticipantPublicKey",
    "SwapMessageBindings",
    "DropMessageBinding",
    "VerifySignaturesFixture",
    "VerifySignaturesTest",
    "SetProposerIndex",
    "ClearFirstAttestationBits",
    "CorruptProof",
    "AppendPhantomAttestation",
    "MutateStateRoot",
    "SwapFirstTwoAttestations",
    "SSZFixture",
    "SSZTest",
    "NetworkingCodecFixture",
    "NetworkingCodecTest",
    "GossipsubHandlerFixture",
    "GossipsubHandlerTest",
    "ApiEndpointFixture",
    "ApiEndpointTest",
    "SlotClockFixture",
    "SlotClockTest",
    "JustifiabilityFixture",
    "JustifiabilityTest",
    "PoseidonPermutationFixture",
    "PoseidonPermutationTest",
    "SyncFixture",
    "SyncTest",
    # Test types
    "BaseForkChoiceStep",
    "TickStep",
    "BlockStep",
    "AttestationStep",
    "GossipAggregatedAttestationStep",
    "ForkChoiceStep",
    "StateExpectation",
    "StoreChecks",
    "StoreSnapshot",
    "AttestationCheck",
    "AggregatedAttestationCheck",
    # Type aliases for test function signatures
    "StateTransitionTestFiller",
    "ForkChoiceTestFiller",
    "VerifySingleMessageProofsTestFiller",
    "VerifyMultiMessageProofsTestFiller",
    "VerifySignaturesTestFiller",
    "SSZTestFiller",
    "NetworkingCodecTestFiller",
    "GossipsubHandlerTestFiller",
    "ApiEndpointTestFiller",
    "SlotClockTestFiller",
    "JustifiabilityTestFiller",
    "PoseidonPermutationTestFiller",
    "SyncTestFiller",
    "ReaggregationTestFiller",
]
